version: "3"
services:
  transaction:
    build: .
    environment:
      - AWS_REGION="sa-east-1"
      - AWS_ENDPOINT="http://localstack:4566"
      - AWS_CREDENTIALS_ACCESS_KEY_ID="default_access_key"
      - AWS_CREDENTIALS_SECRET_ACCESS_KEY="default_secret_key"
    ports:
      - "50051:50051"
    depends_on:
      - localstack
    command: "npm run start:dev"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
    environment:
      - SERVICES=dynamodb
      - DATA_DIR=/tmp/localstack/data
      - DYNAMODB_SHARE_DB=1
      - HOSTNAME_EXTERNAL=localstack
